CREATE TABLE [web].[RepRoster] (
    [RepRosterId]          INT            IDENTITY (1, 1) NOT NULL,
    [RepRosterFeedId]      INT            NOT NULL,
    [EmployeeId]           NVARCHAR (200) NOT NULL,
    [Version]              INT            NOT NULL,
    [StartDate]            DATE           NOT NULL,
    [EndDate]              DATE           NULL,
    [TerritoryNumber]      NVARCHAR (200) NULL,
    [TerritoryName]        NVARCHAR (200) NULL,
    [TerritoryDisplayName] NVARCHAR (400) NULL,
    [Area]                 NVARCHAR (200) NULL,
    [Region]               NVARCHAR (200) NULL,
    [FirstName]            NVARCHAR (200) NOT NULL,
    [MiddleName]           NVARCHAR (200) NULL,
    [LastName]             NVARCHAR (200) NOT NULL,
    [NickName]             NVARCHAR (200) NULL,
    [MangerEmployeeId]     NVARCHAR (200) NULL,
    [MangerEmployeeName]   NVARCHAR (200) NULL,
    [MobilePhone]          NVARCHAR (50)  NULL,
    [WorkPhone]            NVARCHAR (50)  NULL,
    [WorkEmail]            NVARCHAR (MAX) NULL,
    [PersonalEmail]        NVARCHAR (MAX) NULL,
    [HireDate]             DATETIME       NULL,
    [RelievingDate]        DATETIME       NULL,
    [TimeZone]             NVARCHAR (200) NULL,
    [Address]              NVARCHAR (MAX) NULL,
    [City]                 NVARCHAR (200) NULL,
    [State]                NVARCHAR (200) NULL,
    [Country]              NVARCHAR (200) NULL,
    [ZipCode]              NVARCHAR (50)  NULL,
    [StorageLockerAddress] NVARCHAR (MAX) NULL,
    [StorageLockerCity]    NVARCHAR (200) NULL,
    [StorageLockerState]   NVARCHAR (200) NULL,
    [StorageLockerCountry] NVARCHAR (200) NULL,
    [StorageLockerZipCode] NVARCHAR (50)  NULL,
    [Team]                 NVARCHAR (200) NULL,
    [Role]                 NVARCHAR (200) NULL,
    [VeevaUserId]          NVARCHAR (200) NULL,
    [VeevaTerritoryId]     NVARCHAR (200) NULL,
    [VeevaRoleId]          NVARCHAR (200) NULL,
    [Extra1]               NVARCHAR (200) NULL,
    [Extra2]               NVARCHAR (200) NULL,
    [Extra3]               NVARCHAR (200) NULL,
    [Extra4]               NVARCHAR (200) NULL,
    [Extra5]               NVARCHAR (200) NULL,
    [CreatedBy]            INT            NOT NULL,
    [CreatedDate]          DATETIME       NOT NULL,
    [UpdatedBy]            INT            NOT NULL,
    [LastUpdatedDate]      DATETIME       NOT NULL,
    [DisplayAddress]       AS             (concat_ws(', ',[Address],[City],[State],[Country],[ZipCode])),
    [DisplayName]          AS             (concat_ws(', ',[FirstName],[LastName])),
    PRIMARY KEY CLUSTERED ([RepRosterId] ASC),
    CONSTRAINT [FK_RepRoster_RepRosterFeedId] FOREIGN KEY ([RepRosterFeedId]) REFERENCES [web].[RepRosterFeed] ([RepRosterFeedId]),
    CONSTRAINT [RepRoster_EmployeeId_Version_StartDate] UNIQUE NONCLUSTERED ([EmployeeId] ASC, [Version] ASC, [StartDate] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RepRoster_RepRosterFeedId]
    ON [web].[RepRoster]([RepRosterFeedId] ASC);

