CREATE TABLE [dbo].[Call] (
    [Id]                         INT              IDENTITY (1, 1) NOT NULL,
    [EndDate]                    DATETIME         NULL,
    [CreatedDate]                DATETIME         NULL,
    [UpdatedDate]                DATETIME         NULL,
    [ExternalId1]                VARCHAR (400)    NULL,
    [CallId]                     UNIQUEIDENTIFIER NULL,
    [OwnerId]                    VARCHAR (400)    NULL,
    [IsDeleted]                  VARCHAR (400)    NULL,
    [Name]                       VARCHAR (400)    NULL,
    [RecordTypeId]               VARCHAR (400)    NULL,
    [VeevaCreatedDate]           VARCHAR (400)    NULL,
    [VeevaCreatedById]           VARCHAR (400)    NULL,
    [LastModifiedDate]           VARCHAR (400)    NULL,
    [LastModifiedById]           VARCHAR (400)    NULL,
    [SystemModstamp]             VARCHAR (400)    NULL,
    [LastActivityDate]           VARCHAR (400)    NULL,
    [MayEdit]                    VARCHAR (400)    NULL,
    [IsLocked]                   VARCHAR (400)    NULL,
    [LastViewedDate]             VARCHAR (400)    NULL,
    [LastReferencedDate]         VARCHAR (400)    NULL,
    [CallComments]               VARCHAR (400)    NULL,
    [SampleCard]                 VARCHAR (400)    NULL,
    [AddDetail]                  VARCHAR (400)    NULL,
    [Property]                   VARCHAR (400)    NULL,
    [Account]                    VARCHAR (400)    NULL,
    [Status]                     VARCHAR (400)    NULL,
    [ParentAddress]              VARCHAR (400)    NULL,
    [AccountPlan]                VARCHAR (400)    NULL,
    [NextCallNotes]              VARCHAR (400)    NULL,
    [PreCallNotes]               VARCHAR (400)    NULL,
    [MobileID]                   VARCHAR (400)    NULL,
    [ActivityTypec]              VARCHAR (400)    NULL,
    [SignificantEventc]          VARCHAR (400)    NULL,
    [Location]                   VARCHAR (400)    NULL,
    [Subject]                    VARCHAR (400)    NULL,
    [Unlock]                     VARCHAR (400)    NULL,
    [CallDatetime]               VARCHAR (400)    NULL,
    [DisbursedTo]                VARCHAR (400)    NULL,
    [Disclaimer]                 VARCHAR (400)    NULL,
    [RequestReceipt]             VARCHAR (400)    NULL,
    [SignatureDate]              VARCHAR (400)    NULL,
    [Territory]                  VARCHAR (400)    NULL,
    [SubmittedByMobile]          VARCHAR (400)    NULL,
    [CallType]                   VARCHAR (400)    NULL,
    [AddKeyMessage]              VARCHAR (400)    NULL,
    [Address]                    VARCHAR (400)    NULL,
    [Attendees]                  VARCHAR (400)    NULL,
    [AttendeeType]               VARCHAR (400)    NULL,
    [CallDate]                   VARCHAR (400)    NULL,
    [DetailedProducts]           VARCHAR (400)    NULL,
    [NoDisbursement]             VARCHAR (400)    NULL,
    [ParentCall]                 VARCHAR (400)    NULL,
    [User]                       VARCHAR (400)    NULL,
    [Contact]                    VARCHAR (400)    NULL,
    [MedicalEvent]               VARCHAR (400)    NULL,
    [MobileVeevaCreatedDatetime] VARCHAR (400)    NULL,
    [MobileLastModifiedDatetime] VARCHAR (400)    NULL,
    [License]                    VARCHAR (400)    NULL,
    [IsParentCall]               VARCHAR (400)    NULL,
    [EntityDisplayName]          VARCHAR (400)    NULL,
    [OverrideLock]               VARCHAR (400)    NULL,
    [LastDevice]                 VARCHAR (400)    NULL,
    [ShipAddressLine1]           VARCHAR (400)    NULL,
    [ShipAddressLine2]           VARCHAR (400)    NULL,
    [ShipCity]                   VARCHAR (400)    NULL,
    [ShipCountry]                VARCHAR (400)    NULL,
    [ShipLicenseExpirationDate]  VARCHAR (400)    NULL,
    [ShipLicenseStatus]          VARCHAR (400)    NULL,
    [ShipLicense]                VARCHAR (400)    NULL,
    [ShipState]                  VARCHAR (400)    NULL,
    [ShipToAddress]              VARCHAR (400)    NULL,
    [ShipZip]                    VARCHAR (400)    NULL,
    [ShipToAddressText]          VARCHAR (400)    NULL,
    [CLM]                        VARCHAR (400)    NULL,
    [zvodCLMDetails]             VARCHAR (400)    NULL,
    [IsSampledCall]              VARCHAR (400)    NULL,
    [Presentations]              VARCHAR (400)    NULL,
    [EntityReferenceId]          VARCHAR (400)    NULL,
    [ErrorReferenceCall]         VARCHAR (400)    NULL,
    [Duration]                   VARCHAR (400)    NULL,
    [Color]                      VARCHAR (400)    NULL,
    [AllowedProducts]            VARCHAR (400)    NULL,
    [zvodAttachments]            VARCHAR (400)    NULL,
    [SampleCardReason]           VARCHAR (400)    NULL,
    [ASSMCA]                     VARCHAR (400)    NULL,
    [AddressLine1]               VARCHAR (400)    NULL,
    [AddressLine2]               VARCHAR (400)    NULL,
    [City]                       VARCHAR (400)    NULL,
    [DEAAddressLine1]            VARCHAR (400)    NULL,
    [DEAAddressLine2]            VARCHAR (400)    NULL,
    [DEAAddress]                 VARCHAR (400)    NULL,
    [DEACity]                    VARCHAR (400)    NULL,
    [DEAExpirationDate]          VARCHAR (400)    NULL,
    [DEAState]                   VARCHAR (400)    NULL,
    [DEAZip4]                    VARCHAR (400)    NULL,
    [DEAZip]                     VARCHAR (400)    NULL,
    [DEA]                        VARCHAR (400)    NULL,
    [ShipZip4]                   VARCHAR (400)    NULL,
    [State]                      VARCHAR (400)    NULL,
    [Zip4]                       VARCHAR (400)    NULL,
    [Zip]                        VARCHAR (400)    NULL,
    [SampleSendCard]             VARCHAR (400)    NULL,
    [Credentials]                VARCHAR (400)    NULL,
    [Salutation]                 VARCHAR (400)    NULL,
    [ProductPriority1]           VARCHAR (400)    NULL,
    [ProductPriority2]           VARCHAR (400)    NULL,
    [ProductPriority3]           VARCHAR (400)    NULL,
    [ProductPriority4]           VARCHAR (400)    NULL,
    [ProductPriority5]           VARCHAR (400)    NULL,
    [ExpenseAmount]              VARCHAR (400)    NULL,
    [TotalExpenseAttendeesCount] VARCHAR (400)    NULL,
    [Attendeelist]               VARCHAR (400)    NULL,
    [ExpensePostStatus]          VARCHAR (400)    NULL,
    [AttendeePostStatus]         VARCHAR (400)    NULL,
    [ExpenseSystemExternalID]    VARCHAR (400)    NULL,
    [IncurredExpense]            VARCHAR (400)    NULL,
    [LocationServicesStatus]     VARCHAR (400)    NULL,
    [ParentCallMobileID]         VARCHAR (400)    NULL,
    [RemoteMeeting]              VARCHAR (400)    NULL,
    [VeevaRemoteMeetingId]       VARCHAR (400)    NULL,
    [CNXChannelc]                VARCHAR (400)    NULL,
    [CNXDurationc]               VARCHAR (400)    NULL,
    CONSTRAINT [PK_Call] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_Call_VeevaCreatedById]
    ON [dbo].[Call]([VeevaCreatedById] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Call_Account]
    ON [dbo].[Call]([Account] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Call_Territory]
    ON [dbo].[Call]([Territory] ASC);

