CREATE TABLE [dbo].[CallSample] (
    [Id]                 INT              IDENTITY (1, 1) NOT NULL,
    [EndDate]            DATETIME         NULL,
    [CreatedDate]        DATETIME         NULL,
    [UpdatedDate]        DATETIME         NULL,
    [ExternalId1]        VARCHAR (400)    NULL,
    [CallSampleId]       UNIQUEIDENTIFIER NULL,
    [IsDeleted]          VARCHAR (400)    NULL,
    [Name]               VARCHAR (400)    NULL,
    [VeevaCreatedDate]   VARCHAR (400)    NULL,
    [VeevaCreatedById]   VARCHAR (400)    NULL,
    [LastModifiedDate]   VARCHAR (400)    NULL,
    [LastModifiedById]   VARCHAR (400)    NULL,
    [SystemModstamp]     VARCHAR (400)    NULL,
    [LastActivityDate]   VARCHAR (400)    NULL,
    [MayEdit]            VARCHAR (400)    NULL,
    [IsLocked]           VARCHAR (400)    NULL,
    [LastViewedDate]     VARCHAR (400)    NULL,
    [LastReferencedDate] VARCHAR (400)    NULL,
    [Account]            VARCHAR (400)    NULL,
    [CallDate]           VARCHAR (400)    NULL,
    [IsParentCall]       VARCHAR (400)    NULL,
    [Quantity]           VARCHAR (400)    NULL,
    [Lot]                VARCHAR (400)    NULL,
    [MobileID]           VARCHAR (400)    NULL,
    [Call2]              VARCHAR (400)    NULL,
    [Product]            VARCHAR (400)    NULL,
    [OverrideLock]       VARCHAR (400)    NULL,
    [Distributor]        VARCHAR (400)    NULL,
    [AttendeeType]       VARCHAR (400)    NULL,
    [EntityReferenceId]  VARCHAR (400)    NULL,
    [DeliveryStatus]     VARCHAR (400)    NULL,
    [ApplyLimit]         VARCHAR (400)    NULL,
    [LimitApplied]       VARCHAR (400)    NULL,
    [Manufacturer]       VARCHAR (400)    NULL,
    [Call2MobileID]      VARCHAR (400)    NULL,
    CONSTRAINT [PK_CallSample] PRIMARY KEY CLUSTERED ([Id] ASC)
);

