CREATE TABLE [dbo].[CMS_Account] (
    [CmsId]                            INT              IDENTITY (1, 1) NOT NULL,
    [OdsId]                            UNIQUEIDENTIFIER NULL,
    [VeevaId]                          NVARCHAR (20)    NULL,
    [XPOPrescriberNo]                  NVARCHAR (20)    NULL,
    [DDDOutletZipId]                   NVARCHAR (20)    NULL,
    [Source]                           NVARCHAR (4)     NOT NULL,
    [AccountType]                      NVARCHAR (100)   NULL,
    [AccountSubType]                   NVARCHAR (80)    NULL,
    [ExternalId2]                      NVARCHAR (200)   NULL,
    [ExternalId3]                      NVARCHAR (200)   NULL,
    [Status]                           NVARCHAR (80)    NULL,
    [ComputedStatus]                   NVARCHAR (80)    NULL,
    [FirstName]                        NVARCHAR (400)   NULL,
    [LastName]                         NVARCHAR (400)   NULL,
    [MiddleName]                       NVARCHAR (400)   NULL,
    [Name]                             NVARCHAR (400)   NULL,
    [AlternateName]                    NVARCHAR (400)   NULL,
    [FormattedName]                    NVARCHAR (400)   NULL,
    [PreferredName]                    NVARCHAR (400)   NULL,
    [Suffix]                           NVARCHAR (80)    NULL,
    [Title]                            NVARCHAR (200)   NULL,
    [Salutation]                       NVARCHAR (80)    NULL,
    [Gender]                           NVARCHAR (80)    NULL,
    [DateOfBirth]                      DATE             NULL,
    [IsPerson]                         BIT              NULL,
    [PracticeAtHospital]               NVARCHAR (80)    NULL,
    [NumberOfDepartments]              NUMERIC (18)     NULL,
    [AccountDescription]               NVARCHAR (200)   NULL,
    [IMSId]                            NVARCHAR (200)   NULL,
    [MENumber]                         NVARCHAR (200)   NULL,
    [AHANumber]                        NVARCHAR (200)   NULL,
    [NPINumber]                        NVARCHAR (200)   NULL,
    [DEA]                              NVARCHAR (50)    NULL,
    [HIN]                              NVARCHAR (50)    NULL,
    [ClientAccountId]                  NVARCHAR (200)   NULL,
    [ClientExtraId]                    NVARCHAR (200)   NULL,
    [ClientExtraId2]                   NVARCHAR (200)   NULL,
    [ProfessionalDesignation]          NVARCHAR (50)    NULL,
    [PDRPOptOutFlag]                   NVARCHAR (4)     NULL,
    [RecordTypeId]                     NVARCHAR (50)    NULL,
    [IsLocked]                         BIT              NULL,
    [MayEdit]                          BIT              NULL,
    [IsDeleted]                        BIT              NULL,
    [Phone]                            NVARCHAR (50)    NULL,
    [Fax]                              NVARCHAR (50)    NULL,
    [Specialty1]                       NVARCHAR (200)   NULL,
    [Specialty2]                       NVARCHAR (200)   NULL,
    [PrimaryParentAccount_ExternalId1] NVARCHAR (200)   NULL,
    [CreatedUtcDate]                   DATETIME         NOT NULL,
    [ExternalUpdatedUtcDate]           DATETIME         NULL,
    [VeevaUpdatedUtcDate]              DATETIME         NULL,
    [UpdatedBy]                        INT              NULL,
    [EndUtcDate]                       DATETIME         NULL,
    [DoNotCall]                        NVARCHAR (50)    NULL,
    [Credentials]                      NVARCHAR (50)    NULL,
    [GenText1]                         NVARCHAR (500)   NULL,
    [GenText2]                         NVARCHAR (500)   NULL,
    [GenText3]                         NVARCHAR (500)   NULL,
    [GenText4]                         NVARCHAR (500)   NULL,
    [GenText5]                         NVARCHAR (500)   NULL,
    [GenText6]                         NVARCHAR (500)   NULL,
    [GenText7]                         NVARCHAR (500)   NULL,
    [GenText8]                         NVARCHAR (500)   NULL,
    [GenText9]                         NVARCHAR (500)   NULL,
    [GenText10]                        NVARCHAR (500)   NULL,
    [GenText11]                        NVARCHAR (500)   NULL,
    [GenText12]                        NVARCHAR (500)   NULL,
    [GenText13]                        NVARCHAR (500)   NULL,
    [GenText14]                        NVARCHAR (500)   NULL,
    [GenText15]                        NVARCHAR (500)   NULL,
    [GenText16]                        NVARCHAR (500)   NULL,
    [GenText17]                        NVARCHAR (500)   NULL,
    [GenText18]                        NVARCHAR (500)   NULL,
    [GenText19]                        NVARCHAR (500)   NULL,
    [GenText20]                        NVARCHAR (500)   NULL,
    [GenInteger1]                      INT              NULL,
    [GenInteger2]                      INT              NULL,
    [GenInteger3]                      INT              NULL,
    [GenInteger4]                      INT              NULL,
    [GenInteger5]                      INT              NULL,
    [GenBoolean1]                      BIT              NULL,
    [GenBoolean2]                      BIT              NULL,
    [GenBoolean3]                      BIT              NULL,
    [GenBoolean4]                      BIT              NULL,
    [GenBoolean5]                      BIT              NULL,
    [GenBoolean6]                      BIT              NULL,
    [GenBoolean7]                      BIT              NULL,
    [GenBoolean8]                      BIT              NULL,
    [GenBoolean9]                      BIT              NULL,
    [GenBoolean10]                     BIT              NULL,
    [GenBoolean11]                     BIT              NULL,
    [GenBoolean12]                     BIT              NULL,
    [GenBoolean13]                     BIT              NULL,
    [GenBoolean14]                     BIT              NULL,
    [GenBoolean15]                     BIT              NULL,
    [GenBoolean16]                     BIT              NULL,
    [GenBoolean17]                     BIT              NULL,
    [GenBoolean18]                     BIT              NULL,
    [GenBoolean19]                     BIT              NULL,
    [GenBoolean20]                     BIT              NULL,
    [GenBoolean21]                     BIT              NULL,
    [GenBoolean22]                     BIT              NULL,
    [GenBoolean23]                     BIT              NULL,
    [GenBoolean24]                     BIT              NULL,
    [GenBoolean25]                     BIT              NULL,
    [GenDecimal1]                      DECIMAL (18, 4)  NULL,
    [GenDecimal2]                      DECIMAL (18, 4)  NULL,
    [GenDecimal3]                      DECIMAL (18, 4)  NULL,
    [GenDecimal4]                      DECIMAL (18, 4)  NULL,
    [GenDecimal5]                      DECIMAL (18, 4)  NULL,
    [GenDateTime1]                     DATETIME         NULL,
    [GenDateTime2]                     DATETIME         NULL,
    [GenDateTime3]                     DATETIME         NULL,
    [GenDateTime4]                     DATETIME         NULL,
    [GenDateTime5]                     DATETIME         NULL,
    [GenText21]                        NVARCHAR (500)   NULL,
    [GenText22]                        NVARCHAR (500)   NULL,
    [GenText23]                        NVARCHAR (500)   NULL,
    [GenText24]                        NVARCHAR (500)   NULL,
    [GenText25]                        NVARCHAR (500)   NULL,
    [GenText26]                        NVARCHAR (500)   NULL,
    [GenText27]                        NVARCHAR (500)   NULL,
    [GenText28]                        NVARCHAR (500)   NULL,
    [GenText29]                        NVARCHAR (500)   NULL,
    [GenText30]                        NVARCHAR (500)   NULL,
    [GenBoolean26]                     BIT              NULL,
    [GenBoolean27]                     BIT              NULL,
    [GenBoolean28]                     BIT              NULL,
    [GenBoolean29]                     BIT              NULL,
    [GenBoolean30]                     BIT              NULL,
    [GenDateTime6]                     DATETIME         NULL,
    [GenDateTime7]                     DATETIME         NULL,
    [GenDateTime8]                     DATETIME         NULL,
    [GenDateTime9]                     DATETIME         NULL,
    [GenDateTime10]                    DATETIME         NULL,
    CONSTRAINT [PK_CMS_Account] PRIMARY KEY CLUSTERED ([CmsId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CMS_Account_AccountType]
    ON [dbo].[CMS_Account]([AccountType] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CMS_Account_Specialty1]
    ON [dbo].[CMS_Account]([Specialty1] ASC);

