CREATE TABLE [dbo].[Reporting_SL_FullReportData] (
    [UserId]                                        UNIQUEIDENTIFIER NULL,
    [AccountId]                                     UNIQUEIDENTIFIER NULL,
    [TerritoryId]                                   UNIQUEIDENTIFIER NULL,
    [Territory Name]                                NVARCHAR (400)   NULL,
    [Target Type]                                   VARCHAR (20)     NULL,
    [TargetTypeInteger]                             INT              NULL,
    [HCP Name]                                      NVARCHAR (400)   NULL,
    [Speciality]                                    NVARCHAR (100)   NULL,
    [Sample/TRx Range]                              NVARCHAR (20)    NULL,
    [Sample/TRx]                                    DECIMAL (10, 2)  NULL,
    [Total Samples]                                 INT              NULL,
    [Total TRx]                                     INT              NULL,
    [Samples/Call]                                  DECIMAL (10, 2)  NULL,
    [Sample Calls]                                  INT              NULL,
    [Presentation Calls]                            INT              NULL,
    [Total Calls]                                   INT              NULL,
    [Concyn Sample, .5oz (14g) Samples]             INT              NULL,
    [Concyn Sample, .5oz (14g) TRx]                 INT              NULL,
    [Concyn Trade, 1 oz (28g) Samples]              INT              NULL,
    [Concyn Trade, 1 oz (28g) TRx]                  INT              NULL,
    [Congra - 100 MG Samples]                       INT              NULL,
    [Congra - 100 MG TRx]                           INT              NULL,
    [Congra - 50 MG Samples]                        INT              NULL,
    [Congra - 50 MG TRx]                            INT              NULL,
    [Congra - 75 MG Samples]                        INT              NULL,
    [Congra - 75 MG TRx]                            INT              NULL,
    [Conmax - Cream, 10ml Samples]                  INT              NULL,
    [Conmax - Cream, 10ml TRx]                      INT              NULL,
    [Convicyn Antipruritic Gel, 1.75oz Samples]     INT              NULL,
    [Convicyn Antipruritic Gel, 1.75oz TRx]         INT              NULL,
    [Convicyn Antipuritic Gel, 6oz Samples]         INT              NULL,
    [Convicyn Antipuritic Gel, 6oz TRx]             INT              NULL,
    [Convicyn Antipuritic Spray, 1.75 floz Samples] INT              NULL,
    [Convicyn Antipuritic Spray, 1.75 floz TRx]     INT              NULL,
    [Convicyn Antipuritic Spray, 6oz Samples]       INT              NULL,
    [Convicyn Antipuritic Spray, 6oz TRx]           INT              NULL,
    [MONDOXYNE 50MG Samples]                        INT              NULL,
    [MONDOXYNE 50MG TRx]                            INT              NULL,
    [MONDOXYNE 75MG Samples]                        INT              NULL,
    [MONDOXYNE 75MG TRx]                            INT              NULL,
    [SEBUDERM Samples]                              INT              NULL,
    [SEBUDERM TRx]                                  INT              NULL
);

