CREATE TABLE [dbo].[Staging_CallSample] (
    [Id]                         VARCHAR (400) NOT NULL,
    [IsDeleted]                  VARCHAR (400) NULL,
    [Name]                       VARCHAR (400) NULL,
    [CreatedDate]                VARCHAR (400) NULL,
    [CreatedById]                VARCHAR (400) NULL,
    [LastModifiedDate]           VARCHAR (400) NULL,
    [LastModifiedById]           VARCHAR (400) NULL,
    [SystemModstamp]             VARCHAR (400) NULL,
    [LastActivityDate]           VARCHAR (400) NULL,
    [MayEdit]                    VARCHAR (400) NULL,
    [IsLocked]                   VARCHAR (400) NULL,
    [LastViewedDate]             VARCHAR (400) NULL,
    [LastReferencedDate]         VARCHAR (400) NULL,
    [Account_vod__c]             VARCHAR (400) NULL,
    [Call_Date_vod__c]           VARCHAR (400) NULL,
    [Is_Parent_Call_vod__c]      VARCHAR (400) NULL,
    [Quantity_vod__c]            VARCHAR (400) NULL,
    [Lot_vod__c]                 VARCHAR (400) NULL,
    [Mobile_ID_vod__c]           VARCHAR (400) NULL,
    [Call2_vod__c]               VARCHAR (400) NULL,
    [Product_vod__c]             VARCHAR (400) NULL,
    [Override_Lock_vod__c]       VARCHAR (400) NULL,
    [Distributor_vod__c]         VARCHAR (400) NULL,
    [Attendee_Type_vod__c]       VARCHAR (400) NULL,
    [Entity_Reference_Id_vod__c] VARCHAR (400) NULL,
    [Delivery_Status_vod__c]     VARCHAR (400) NULL,
    [Apply_Limit_vod__c]         VARCHAR (400) NULL,
    [Limit_Applied_vod__c]       VARCHAR (400) NULL,
    [Manufacturer_vod__c]        VARCHAR (400) NULL,
    [Call2_Mobile_ID_vod__c]     VARCHAR (400) NULL,
    CONSTRAINT [PK_Staging_CallSample] PRIMARY KEY CLUSTERED ([Id] ASC)
);

