
CREATE   PROCEDURE [dbo].[sp_account_transform] 
AS
BEGIN

	INSERT INTO LogMessage(ProcedureName, Comments, LogUTCDate) VALUES('sp_account_transform', 'Started', GETUTCDATE());


	UPDATE P SET 
		P.UpdatedDate = GETDATE(),
		P.ExternalId1 = S.Id,
		P.IsDeleted = S.IsDeleted,
		P.MasterRecordId = S.MasterRecordId,
		P.Name = S.Name,
		P.LastName = S.LastName,
		P.FirstName = S.FirstName,
		P.Salutation = S.Salutation,
		P.RecordTypeId = S.RecordTypeId,
		P.ParentId = S.ParentId,
		P.Phone = S.Phone,
		P.Fax = S.Fax,
		P.Website = S.Website,
		P.NumberOfEmployees = S.NumberOfEmployees,
		P.Ownership = S.Ownership,
		P.OwnerId = S.OwnerId,
		P.VeevaCreatedDate = S.CreatedDate,
		P.VeevaCreatedById = S.CreatedById,
		P.LastModifiedDate = S.LastModifiedDate,
		P.LastModifiedById = S.LastModifiedById,
		P.SystemModstamp = S.SystemModstamp,
		P.LastActivityDate = S.LastActivityDate,
		P.MayEdit = S.MayEdit,
		P.IsLocked = S.IsLocked,
		P.LastViewedDate = S.LastViewedDate,
		P.LastReferencedDate = S.LastReferencedDate,
		P.PersonContactId = S.PersonContactId,
		P.IsPersonAccount = S.IsPersonAccount,
		P.PersonMailingStreet = S.PersonMailingStreet,
		P.PersonMailingCity = S.PersonMailingCity,
		P.PersonMailingState = S.PersonMailingState,
		P.PersonMailingPostalCode = S.PersonMailingPostalCode,
		P.PersonMailingCountry = S.PersonMailingCountry,
		P.PersonOtherStreet = S.PersonOtherStreet,
		P.PersonOtherCity = S.PersonOtherCity,
		P.PersonOtherState = S.PersonOtherState,
		P.PersonOtherPostalCode = S.PersonOtherPostalCode,
		P.PersonOtherCountry = S.PersonOtherCountry,
		P.PersonMobilePhone = S.PersonMobilePhone,
		P.PersonHomePhone = S.PersonHomePhone,
		P.PersonOtherPhone = S.PersonOtherPhone,
		P.PersonAssistantPhone = S.PersonAssistantPhone,
		P.PersonEmail = S.PersonEmail,
		P.PersonTitle = S.PersonTitle,
		P.PersonDepartment = S.PersonDepartment,
		P.PersonAssistantName = S.PersonAssistantName,
		P.PersonBirthdate = S.PersonBirthdate,
		P.PersonHasOptedOutOfEmail = S.PersonHasOptedOutOfEmail,
		P.PersonHasOptedOutOfFax = S.PersonHasOptedOutOfFax,
		P.PersonDoNotCall = S.PersonDoNotCall,
		P.PersonLastCURequestDate = S.PersonLastCURequestDate,
		P.PersonLastCUUpdateDate = S.PersonLastCUUpdateDate,
		P.PersonEmailBouncedReason = S.PersonEmailBouncedReason,
		P.PersonEmailBouncedDate = S.PersonEmailBouncedDate,
		P.PersonIndividualId = S.PersonIndividualId,
		P.AccountSource = S.AccountSource,
		P.ExternalID = S.External_ID_vod__c,
		P.Credentials = S.Credentials_vod__c,
		P.Territory = S.Territory_vod__c,
		P.ExcludefromZiptoTerrProcessing = S.Exclude_from_Zip_to_Terr_Processing_vod__c,
		P.GroupSpecialty1 = S.Group_Specialty_1_vod__c,
		P.GroupSpecialty2 = S.Group_Specialty_2_vod__c,
		P.Specialty1 = S.Specialty_1_vod__c,
		P.Specialty2 = S.Specialty_2_vod__c,
		P.FormattedName = S.Formatted_Name_vod__c,
		P.TerritoryTest = S.Territory_Test_vod__c,
		P.MobileID = S.Mobile_ID_vod__c,
		P.Gender = S.Gender_vod__c,
		P.ExternalId2 = S.ID_vod__c,
		P.DoNotSyncSalesData = S.Do_Not_Sync_Sales_Data_vod__c,
		P.ID2 = S.ID2_vod__c,
		P.PreferredName = S.Preferred_Name_vod__c,
		P.SampleDefault = S.Sample_Default_vod__c,
		P.Segmentations = S.Segmentations_vod__c,
		P.RestrictedProducts = S.Restricted_Products_vod__c,
		P.PayerId = S.Payer_Id_vod__c,
		P.AlternateName = S.Alternate_Name_vod__c,
		P.DoNotCall = S.Do_Not_Call_vod__c,
		P.Bedsc = S.Beds__c,
		P.SpendAmountc = S.Spend_Amount__c,
		P.PDRPOptOut = S.PDRP_Opt_Out_vod__c,
		P.SpendStatusValue = S.Spend_Status_Value_vod__c,
		P.PDRPOptOutDate = S.PDRP_Opt_Out_Date_vod__c,
		P.SpendStatus = S.Spend_Status_vod__c,
		P.EnableRestrictedProducts = S.Enable_Restricted_Products_vod__c,
		P.CallReminder = S.Call_Reminder_vod__c,
		P.AccountGroup = S.Account_Group_vod__c,
		P.PrimaryParent = S.Primary_Parent_vod__c,
		P.Color = S.Color_vod__c,
		P.Middle = S.Middle_vod__c,
		P.Suffix = S.Suffix_vod__c,
		P.NoOrders = S.No_Orders_vod__c,
		P.AccountIdentifier = S.Account_Identifier_vod__c,
		P.ApprovedEmailOptType = S.Approved_Email_Opt_Type_vod__c,
		P.AccountSearchFirstLast = S.Account_Search_FirstLast_vod__c,
		P.AccountSearchLastFirst = S.Account_Search_LastFirst_vod__c,
		P.Language = S.Language_vod__c,
		P.PracticeatHospital = S.Practice_at_Hospital_vod__c,
		P.PracticeNearHospital = S.Practice_Near_Hospital_vod__c,
		P.DoNotCreateChildAccount = S.Do_Not_Create_Child_Account_vod__c,
		P.TotalMDsDOsc = S.Total_MDs_DOs__c,
		P.AHAc = S.AHA__c,
		P.OrderType = S.Order_Type_vod__c,
		P.NPI = S.NPI_vod__c,
		P.MEc = S.ME__c,
		P.Speakerc = S.Speaker__c,
		P.Investigator = S.Investigator_vod__c,
		P.DefaultOrderType = S.Default_Order_Type_vod__c,
		P.TaxStatusc = S.Tax_Status__c,
		P.Modelc = S.Model__c,
		P.Offeringsc = S.Offerings__c,
		P.Departmentsc = S.Departments__c,
		P.AccountTypec = S.Account_Type__c,
		P.AccountSearchBusiness = S.Account_Search_Business_vod__c,
		P.BusinessProfessionalPerson = S.Business_Professional_Person_vod__c,
		P.HospitalType = S.Hospital_Type_vod__c,
		P.AccountClass = S.Account_Class_vod__c,
		P.Furigana = S.Furigana_vod__c,
		P.TotalRevenue000c = S.Total_Revenue_000__c,
		P.NetIncomeLoss000c = S.Net_Income_Loss_000__c,
		P.PMPMIncomeLoss000c = S.PMPM_Income_Loss_000__c,
		P.CommercialPremiumsPMPMc = S.Commercial_Premiums_PMPM__c,
		P.MedicalLossRatioc = S.Medical_Loss_Ratio__c,
		P.MedicalExpensesPMPMc = S.Medical_Expenses_PMPM__c,
		P.CommercialPatientDays1000c = S.Commercial_Patient_Days_1000__c,
		P.HMOMarketShrc = S.HMO_Market_Shr__c,
		P.HMOc = S.HMO__c,
		P.HMOPOSc = S.HMO_POS__c,
		P.PPOc = S.PPO__c,
		P.PPOPOSc = S.PPO_POS__c,
		P.Medicarec = S.Medicare__c,
		P.Medicaidc = S.Medicaid__c,
		P.BusinessDescriptionc = S.Business_Description__c,
		P.RegionalStrategyc = S.Regional_Strategy__c,
		P.ContractsProcessc = S.Contracts_Process__c,
		P.Targetc = S.Target__c,
		P.KOL = S.KOL_vod__c,
		P.TotalLivesc = S.Total_Lives__c,
		P.TotalPhysiciansEnrolledc = S.Total_Physicians_Enrolled__c,
		P.TotalPharmacistsc = S.Total_Pharmacists__c,
		P.CNXAddressc = S.CNX_Address__c,
		P.CNXCRMIDc = S.CNX_CRM_ID__c,
		P.CNXDecilec = S.CNX_Decile__c,
		P.CNXFieldEmailc = S.CNX_Field_Email__c,
		P.CNXFieldPhonec = S.CNX_Field_Phone__c,
		P.CNXPreferredMethodOfContactc = S.CNX_Preferred_Method_Of_Contact__c,
		P.CNXRolec = S.CNX_Role__c,
		P.CNXTargetMSLc = S.CNX_Target_MSL__c,
		P.CNXTargetSSc = S.CNX_Target_SS__c,
		P.CNXTargetTypec = S.CNX_Target_Type__c,
		P.MobileIDvodpc = S.Mobile_ID_vod__pc
	FROM [dbo].[Account] P
	INNER JOIN [dbo].[Staging_Account] S ON S.[Id] = P.[ExternalId1] 
		AND S.SystemModstamp <> P.SystemModstamp AND P.EndDate IS NULL;
		
		

	INSERT INTO [dbo].[Account]
		([AccountId], CreatedDate, 
		ExternalId1, IsDeleted, MasterRecordId, Name, LastName, FirstName, Salutation, 
		RecordTypeId, ParentId, Phone, Fax, Website, NumberOfEmployees, Ownership, 
		OwnerId, VeevaCreatedDate, VeevaCreatedById, LastModifiedDate, LastModifiedById, 
		SystemModstamp, LastActivityDate, MayEdit, IsLocked, LastViewedDate, 
		LastReferencedDate, PersonContactId, IsPersonAccount, PersonMailingStreet, 
		PersonMailingCity, PersonMailingState, PersonMailingPostalCode, PersonMailingCountry, 
		PersonOtherStreet, PersonOtherCity, PersonOtherState, PersonOtherPostalCode, 
		PersonOtherCountry, PersonMobilePhone, PersonHomePhone, PersonOtherPhone, 
		PersonAssistantPhone, PersonEmail, PersonTitle, PersonDepartment, PersonAssistantName, 
		PersonBirthdate, PersonHasOptedOutOfEmail, PersonHasOptedOutOfFax, PersonDoNotCall, 
		PersonLastCURequestDate, PersonLastCUUpdateDate, PersonEmailBouncedReason, 
		PersonEmailBouncedDate, PersonIndividualId, AccountSource, ExternalID, Credentials, 
		Territory, ExcludefromZiptoTerrProcessing, GroupSpecialty1, GroupSpecialty2, Specialty1, 
		Specialty2, FormattedName, TerritoryTest, MobileID, Gender, ExternalId2, 
		DoNotSyncSalesData, ID2, PreferredName, SampleDefault, Segmentations, RestrictedProducts, 
		PayerId, AlternateName, DoNotCall, Bedsc, SpendAmountc, PDRPOptOut, SpendStatusValue, 
		PDRPOptOutDate, SpendStatus, EnableRestrictedProducts, CallReminder, AccountGroup, 
		PrimaryParent, Color, Middle, Suffix, NoOrders, AccountIdentifier, ApprovedEmailOptType, 
		AccountSearchFirstLast, AccountSearchLastFirst, Language, PracticeatHospital, 
		PracticeNearHospital, DoNotCreateChildAccount, TotalMDsDOsc, AHAc, OrderType, NPI, MEc, 
		Speakerc, Investigator, DefaultOrderType, TaxStatusc, Modelc, Offeringsc, Departmentsc, 
		AccountTypec, AccountSearchBusiness, BusinessProfessionalPerson, HospitalType, 
		AccountClass, Furigana, TotalRevenue000c, NetIncomeLoss000c, PMPMIncomeLoss000c, 
		CommercialPremiumsPMPMc, MedicalLossRatioc, MedicalExpensesPMPMc, CommercialPatientDays1000c, 
		HMOMarketShrc, HMOc, HMOPOSc, PPOc, PPOPOSc, Medicarec, Medicaidc, BusinessDescriptionc, 
		RegionalStrategyc, ContractsProcessc, Targetc, KOL, TotalLivesc, TotalPhysiciansEnrolledc, 
		TotalPharmacistsc, CNXAddressc, CNXCRMIDc, CNXDecilec, 
		CNXFieldEmailc, CNXFieldPhonec, CNXPreferredMethodOfContactc, CNXRolec, 
		CNXTargetMSLc, CNXTargetSSc, CNXTargetTypec, MobileIDvodpc)
	SELECT
		NEWID() AS [AccountId], GETDATE(),
		Id, IsDeleted, MasterRecordId, Name, LastName, FirstName, Salutation, 
		RecordTypeId, ParentId, Phone, Fax, Website, NumberOfEmployees, Ownership, 
		OwnerId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, 
		SystemModstamp, LastActivityDate, MayEdit, IsLocked, LastViewedDate, 
		LastReferencedDate, PersonContactId, IsPersonAccount, PersonMailingStreet, 
		PersonMailingCity, PersonMailingState, PersonMailingPostalCode, PersonMailingCountry, 
		PersonOtherStreet, PersonOtherCity, PersonOtherState, PersonOtherPostalCode, 
		PersonOtherCountry, PersonMobilePhone, PersonHomePhone, PersonOtherPhone, 
		PersonAssistantPhone, PersonEmail, PersonTitle, PersonDepartment, PersonAssistantName, 
		PersonBirthdate, PersonHasOptedOutOfEmail, PersonHasOptedOutOfFax, PersonDoNotCall, 
		PersonLastCURequestDate, PersonLastCUUpdateDate, PersonEmailBouncedReason, 
		PersonEmailBouncedDate, PersonIndividualId, AccountSource, External_ID_vod__c, Credentials_vod__c, 
		Territory_vod__c, Exclude_from_Zip_to_Terr_Processing_vod__c, Group_Specialty_1_vod__c, Group_Specialty_2_vod__c, Specialty_1_vod__c, 
		Specialty_2_vod__c, Formatted_Name_vod__c, Territory_Test_vod__c, Mobile_ID_vod__c, Gender_vod__c, ID_vod__c, 
		Do_Not_Sync_Sales_Data_vod__c, ID2_vod__c, Preferred_Name_vod__c, Sample_Default_vod__c, Segmentations_vod__c, Restricted_Products_vod__c, 
		Payer_Id_vod__c, Alternate_Name_vod__c, Do_Not_Call_vod__c, Beds__c, Spend_Amount__c, PDRP_Opt_Out_vod__c, Spend_Status_Value_vod__c, 
		PDRP_Opt_Out_Date_vod__c, Spend_Status_vod__c, Enable_Restricted_Products_vod__c, Call_Reminder_vod__c, Account_Group_vod__c, 
		Primary_Parent_vod__c, Color_vod__c, Middle_vod__c, Suffix_vod__c, No_Orders_vod__c, Account_Identifier_vod__c, Approved_Email_Opt_Type_vod__c, 
		Account_Search_FirstLast_vod__c, Account_Search_LastFirst_vod__c, Language_vod__c, Practice_at_Hospital_vod__c, Practice_Near_Hospital_vod__c, 
		Do_Not_Create_Child_Account_vod__c, Total_MDs_DOs__c, AHA__c, Order_Type_vod__c, NPI_vod__c, ME__c, 
		Speaker__c, Investigator_vod__c, Default_Order_Type_vod__c, Tax_Status__c, Model__c, Offerings__c, Departments__c, 
		Account_Type__c, Account_Search_Business_vod__c, Business_Professional_Person_vod__c, Hospital_Type_vod__c, 
		Account_Class_vod__c, Furigana_vod__c, Total_Revenue_000__c, Net_Income_Loss_000__c, PMPM_Income_Loss_000__c, 
		Commercial_Premiums_PMPM__c, Medical_Loss_Ratio__c, Medical_Expenses_PMPM__c, Commercial_Patient_Days_1000__c, 
		HMO_Market_Shr__c, HMO__c, HMO_POS__c, PPO__c, PPO_POS__c, Medicare__c, Medicaid__c, Business_Description__c, 
		Regional_Strategy__c, Contracts_Process__c, Target__c, KOL_vod__c, Total_Lives__c, Total_Physicians_Enrolled__c, 
		Total_Pharmacists__c, CNX_Address__c, CNX_CRM_ID__c, CNX_Decile__c, 
		CNX_Field_Email__c, CNX_Field_Phone__c, CNX_Preferred_Method_Of_Contact__c, CNX_Role__c, 
		CNX_Target_MSL__c, CNX_Target_SS__c, CNX_Target_Type__c, Mobile_ID_vod__pc
	FROM [Staging_Account] AS S
	WHERE NOT EXISTS (SELECT 1 FROM [Account] P WHERE P.[ExternalId1] = S.[Id] AND P.EndDate IS NULL);
	
	
	ALTER TABLE Account DISABLE TRIGGER trg_Account;

	WITH cte_Account AS
	(
		SELECT ROW_NUMBER() OVER(PARTITION BY AccountId ORDER BY Id DESC) AS RowNum, Id, StartDate, EndDate, AccountId, VeevaCreatedDate
		FROM Account 
		-- WHERE AccountId IN ( '42BF733B-C90D-47AF-AF0E-007241FDB70D', '534BD97C-B3A4-4B89-AB67-00D5D0C4D43F', 'FD0ABCDF-ABC9-4DED-975E-011F5AFE6CAD')
	)
	UPDATE A SET A.StartDate = ISNULL(A2.EndDate, CAST(REPLACE(A1.VeevaCreatedDate, '.0000000', '') AS DATETIME))--SELECT A.Id, A.EndDate, A.VeevaCreatedDate, A1.AccountId, ISNULL(A2.EndDate, A1.VeevaCreatedDate) AS StartDate, A1.EndDate
	FROM Account A
	INNER JOIN cte_Account A1 ON A1.Id = A.Id
	LEFT OUTER JOIN cte_Account A2 ON A1.AccountId = A2.AccountId AND A1.RowNum + 1 = A2.RowNum;

	ALTER TABLE Account ENABLE TRIGGER trg_Account;


	INSERT INTO LogMessage(ProcedureName, Comments, LogUTCDate) VALUES('sp_account_transform', 'Completed', GETUTCDATE());

END

