CREATE TABLE [dbo].[VEEV_User] (
    [UserId]                 UNIQUEIDENTIFIER NULL,
    [City]                   VARCHAR (100)    NULL,
    [Country]                VARCHAR (100)    NULL,
    [CreatedById]            VARCHAR (50)     NULL,
    [CreatedDate]            DATETIME         NULL,
    [Email]                  VARCHAR (200)    NULL,
    [Fax]                    VARCHAR (50)     NULL,
    [FirstName]              VARCHAR (200)    NULL,
    [EndDate]                DATETIME         NULL,
    [ExternalId1]            VARCHAR (50)     NULL,
    [IsActive]               VARCHAR (50)     NULL,
    [LastLoginDate]          DATETIME         NULL,
    [LastModifiedById]       VARCHAR (50)     NULL,
    [LastModifiedDate]       DATETIME         NULL,
    [LastName]               VARCHAR (200)    NULL,
    [LastiPadConnectVersion] VARCHAR (50)     NULL,
    [LastiPadConnect]        DATETIME         NULL,
    [LastiPadiOSVersion]     VARCHAR (50)     NULL,
    [LastiPadSync]           DATETIME         NULL,
    [ManagerId]              VARCHAR (50)     NULL,
    [MobilePhone]            VARCHAR (50)     NULL,
    [Name]                   VARCHAR (200)    NULL,
    [Phone]                  VARCHAR (50)     NULL,
    [PostalCode]             VARCHAR (50)     NULL,
    [PrimaryTerritory]       VARCHAR (200)    NULL,
    [ProfileId]              VARCHAR (50)     NULL,
    [ProfileName]            VARCHAR (200)    NULL,
    [State]                  VARCHAR (100)    NULL,
    [Street]                 VARCHAR (200)    NULL,
    [SystemModstamp]         DATETIME         NULL,
    [TimeZone]               VARCHAR (200)    NULL,
    [Title]                  VARCHAR (200)    NULL,
    [Username]               VARCHAR (200)    NULL,
    [UserRoleId]             VARCHAR (50)     NULL,
    [UserType]               VARCHAR (200)    NULL,
    [CustomerId]             INT              NULL
);

