CREATE TABLE [dbo].[VEEV_SyncTracking] (
    [SyncTrackingId]        UNIQUEIDENTIFIER NULL,
    [ExternalId1]           VARCHAR (50)     NULL,
    [SyncTrackingName]      VARCHAR (200)    NULL,
    [CreatedById]           VARCHAR (50)     NULL,
    [CreatedDate]           DATETIME         NULL,
    [EndDate]               DATETIME         NULL,
    [IsDeleted]             BIT              NULL,
    [LastModifiedById]      VARCHAR (50)     NULL,
    [LastModifiedDate]      DATETIME         NULL,
    [MayEdit]               BIT              NULL,
    [IsLocked]              BIT              NULL,
    [MobileId]              VARCHAR (100)    NULL,
    [Ownerid]               VARCHAR (50)     NULL,
    [NumberofRetries]       DECIMAL (18, 1)  NULL,
    [NumberofUploadErrors]  DECIMAL (18, 1)  NULL,
    [NumberOfUploads]       DECIMAL (18, 1)  NULL,
    [NumberOfVTrans]        DECIMAL (18, 1)  NULL,
    [MediaProcessed]        BIT              NULL,
    [Cancelled]             BIT              NULL,
    [SuccessfulSync]        DECIMAL (18, 1)  NULL,
    [SyncDuration]          DECIMAL (18, 1)  NULL,
    [SyncType]              VARCHAR (50)     NULL,
    [SyncStartDatetime]     DATETIME         NULL,
    [SyncCompletedDatetime] DATETIME         NULL,
    [UploadProcessed]       VARCHAR (20)     NULL,
    [DownloadProcessed]     BIT              NULL,
    [Version]               VARCHAR (50)     NULL,
    [VInsightsProcessed]    BIT              NULL,
    [SystemModstamp]        DATETIME         NULL,
    [CustomerId]            INT              NULL
);

