name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd ibsa_precall_ui
          npm ci
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      
      - name: Build Next.js app
        run: |
          cd ibsa_precall_ui
          npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          NEXT_PUBLIC_BLOB_URL: ${{ secrets.NEXT_PUBLIC_BLOB_URL }}
      
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ibsa-precall-ui'  # Replace with your App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./ibsa_precall_ui
